vim.g.mapleader = " "
vim.g.maplocalleader = " "
require("core.settings").setup()
require("core.options")
require("core.plugins")
require("core.navigation").setup()
require("core.autocmds").setup()
require("config.colorscheme")
require("mason").setup({ ui = { border = "rounded" } })
require("config.completion")
require("config.languages")
require("config.treesitter")
require("config.formatting")
require("config.editor")
require("config.neotree")
require("config.telescope")
require("config.terminal").setup()
require("config.noice")
require("config.ui")
require("config.appearance").setup(require("core.settings").get().terminal_ui)
require("config.frame").setup()
require("config.minimap").setup()
require("config.dashboard")
require("core.keymaps")
