local palette = require("catppuccin.palettes").get_palette("macchiato")
local colors = {
  base = palette.base,
  chrome = palette.crust,
  border = palette.surface1,
  active_border = palette.blue,
  sidebar = palette.mantle,
  surface = palette.mantle,
  overlay = palette.surface0,
  text = palette.text,
  muted = palette.overlay0,
  lavender = palette.lavender,
  teal = palette.teal,
  peach = palette.peach,
  red = palette.red,
}
vim.g.workbench_colors = colors

require("catppuccin").setup({
  flavour = "macchiato",
  transparent_background = false,
  term_colors = true,
  styles = { comments = { "italic" }, keywords = { "italic" } },
  integrations = {
    gitsigns = true,
    neotree = true,
    notify = true,
    noice = true,
    which_key = true,
    treesitter = true,
    blink_cmp = true,
    mini = { enabled = true },
    telescope = { enabled = true },
    native_lsp = { enabled = true },
  },
  custom_highlights = function()
    return {
      Normal = { fg = colors.text, bg = colors.base },
      NormalNC = { fg = colors.text, bg = colors.base },
      NormalFloat = { fg = colors.text, bg = colors.surface },
      FloatBorder = { fg = colors.lavender, bg = colors.surface },
      FloatTitle = { fg = colors.teal, bg = colors.surface, bold = true },
      WinSeparator = { fg = colors.overlay, bg = colors.chrome },
      CursorLine = { bg = palette.surface0 },
      CursorLineNr = { fg = colors.lavender, bold = true },
      LineNr = { fg = palette.surface1 },
      EndOfBuffer = { fg = colors.base },
      NeoTreeNormal = { fg = colors.text, bg = colors.sidebar },
      NeoTreeNormalNC = { fg = colors.text, bg = colors.sidebar },
      NeoTreeEndOfBuffer = { fg = colors.sidebar, bg = colors.sidebar },
      NeoTreeWinSeparator = { fg = colors.border, bg = colors.sidebar },
      NeoTreeDirectoryIcon = { fg = colors.lavender },
      NeoTreeDirectoryName = { fg = colors.lavender },
      NeoTreeRootName = { fg = colors.teal, bold = true },
      NeoTreeIndentMarker = { fg = palette.surface0 },
      NeoTreeExpander = { fg = colors.muted },
      NeoTreeTitleBar = { fg = colors.teal, bg = colors.sidebar, bold = true },
      MiniIndentscopeSymbol = { fg = palette.surface1 },
      MiniStarterHeader = { fg = colors.lavender, bold = true },
      MiniStarterSection = { fg = colors.teal, bold = true },
      MiniStarterFooter = { fg = colors.muted },
      MiniStarterItemPrefix = { fg = colors.lavender },
      MiniStarterCurrent = { bg = colors.overlay, bold = true },
      WinBar = { fg = colors.muted, bg = colors.chrome },
      WinBarNC = { fg = colors.muted, bg = colors.chrome },
      WorkbenchTabJoin = { fg = colors.chrome, bg = colors.base },
      WorkbenchFrame = { fg = colors.border, bg = colors.chrome },
      WorkbenchPaneBorder = { fg = colors.border, bg = colors.chrome },
      WorkbenchDividerGrip = { fg = palette.overlay1, bg = colors.chrome },
      WorkbenchMinimap = { fg = palette.overlay0, bg = colors.base },
      WorkbenchMinimapView = { bg = "#2b2e43" },
      WorkbenchMinimapActive = { bg = "#1b1f32" },
      WorkbenchChrome = { fg = colors.muted, bg = colors.chrome },
      WorkbenchEditorFill = { fg = colors.text, bg = colors.base },
      WorkbenchEditorCut = { fg = colors.chrome, bg = colors.base },
      WorkbenchEditorBorder = { fg = colors.active_border, bg = colors.base },
      WorkbenchEditorTitle = { fg = colors.lavender, bg = colors.base, bold = true },
      WorkbenchTreeFill = { fg = colors.text, bg = colors.sidebar },
      WorkbenchTreeCut = { fg = colors.chrome, bg = colors.sidebar },
      WorkbenchTreeBorder = { fg = colors.border, bg = colors.sidebar },
      WorkbenchTreeTitle = { fg = colors.teal, bg = colors.sidebar, bold = true },
      WorkbenchDashboardBorder = { fg = colors.teal, bg = colors.base },
      WorkbenchSidebarHeader = { fg = colors.lavender, bg = colors.chrome, bold = true },
      WorkbenchTabShelf = { fg = colors.muted, bg = colors.chrome },
      WorkbenchTabActive = { fg = colors.text, bg = colors.base, bold = true },
      WorkbenchTabActiveEdge = { fg = colors.chrome, bg = colors.base },
      WorkbenchTabInactive = { fg = palette.subtext0, bg = palette.mantle },
      WorkbenchTabInactiveEdge = { fg = colors.base, bg = palette.mantle },
      NeoTreeTabActive = { fg = colors.teal, bg = palette.surface0, bold = true },
      NeoTreeTabInactive = { fg = colors.muted, bg = colors.sidebar },
      NeoTreeTabSeparatorActive = { fg = palette.surface0, bg = colors.sidebar },
      NeoTreeTabSeparatorInactive = { fg = colors.sidebar, bg = colors.sidebar },
      NeoTreeCursorLine = { bg = colors.sidebar },
      WorkbenchTreeSelection = { fg = colors.text, bg = palette.surface0, bold = true },
      WorkbenchTreeSelectionCap = { fg = palette.surface0, bg = colors.sidebar },
      NeoTreeGitModified = { fg = colors.peach },
      NeoTreeGitUntracked = { fg = colors.teal },
      NeoTreeFileNameOpened = { fg = colors.text, bold = true },
      NoiceCmdlinePopup = { fg = colors.text, bg = colors.surface },
      NoiceCmdlinePopupBorder = { fg = colors.lavender, bg = colors.surface },
      NoiceCmdlinePopupBorderSearch = { fg = colors.teal, bg = colors.surface },
      NoiceCmdlinePopupTitle = { fg = colors.teal, bg = colors.surface, bold = true },
      NoicePopupmenu = { fg = colors.text, bg = colors.surface },
      NoicePopupmenuBorder = { fg = colors.lavender, bg = colors.surface },
      NeoTreeFloatNormal = { fg = colors.text, bg = colors.surface },
      NeoTreeFloatBorder = { fg = colors.lavender, bg = colors.surface },
      NeoTreeFloatTitle = { fg = colors.teal, bg = colors.surface, bold = true },
      BlinkCmpMenu = { fg = colors.text, bg = colors.surface },
      BlinkCmpMenuBorder = { fg = colors.lavender, bg = colors.surface },
      WorkbenchPath = { fg = colors.muted, bg = colors.base },
      WorkbenchFile = { fg = colors.lavender, bg = colors.base, bold = true },
      DiagnosticVirtualTextError = { fg = colors.red, bg = "NONE" },
      DiagnosticVirtualTextWarn = { fg = colors.peach, bg = "NONE" },
    }
  end,
})
vim.cmd.colorscheme("catppuccin-macchiato")
