require("telescope").setup({
  defaults = {
    prompt_prefix = "   ",
    selection_caret = "❯ ",
    entry_prefix = "  ",
    sorting_strategy = "ascending",
    layout_strategy = "flex",
    layout_config = {
      horizontal = { prompt_position = "top", preview_width = 0.55 },
      vertical = { prompt_position = "top", preview_height = 0.55 },
      flex = { flip_columns = 120 },
      width = 0.88,
      height = 0.82,
    },
    borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
    file_ignore_patterns = {
      "%.git[/\\]",
      "node_modules[/\\]",
      "%.venv[/\\]",
      "__pycache__[/\\]",
      "%.pyc$",
      "%.o$",
      "%.a$",
      "%.so$",
      "%.vcd$",
      "%.fst$",
      "%.wlf$",
    },
    vimgrep_arguments = {
      "rg",
      "--color=never",
      "--no-heading",
      "--with-filename",
      "--line-number",
      "--column",
      "--smart-case",
      "--hidden",
      "--glob",
      "!.git/*",
    },
    mappings = { i = { ["<C-j>"] = "move_selection_next", ["<C-k>"] = "move_selection_previous" } },
  },
  pickers = {
    find_files = { hidden = true },
    buffers = { sort_mru = true, ignore_current_buffer = true },
  },
})
